from __future__ import annotations

import csv
import textwrap
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CheckoutHour:
    time: str
    today: float
    baseline: float
    absolute_deviation: float
    relative_deviation: float
    is_material: bool
    direction: str
    zero_gap: bool
    severity_score: float


@dataclass(frozen=True)
class FocusCluster:
    direction: str
    start_idx: int
    end_idx: int
    score: float
    peak_idx: int
    has_zero_gap: bool


@dataclass(frozen=True)
class Verdict:
    label: str
    level: str
    summary: str
    investigate_first: bool


COLORS = {
    "bg": "#f8f6f1",
    "panel": "#ffffff",
    "panel_border": "#d7d0c5",
    "title": "#1f2937",
    "muted": "#5f6b7a",
    "axis": "#68717d",
    "grid": "#dfe4ea",
    "today": "#0f4c81",
    "baseline": "#6b7280",
    "surge_fill": "#f6d365",
    "surge_stroke": "#b45309",
    "drop_fill": "#f7c6c7",
    "drop_stroke": "#b42318",
    "badge_normal": "#d1fae5",
    "badge_normal_text": "#065f46",
    "badge_watch": "#fde68a",
    "badge_watch_text": "#92400e",
    "badge_recovering": "#dbeafe",
    "badge_recovering_text": "#1d4ed8",
    "badge_investigate now": "#fecaca",
    "badge_investigate now_text": "#991b1b",
}


def _parse_bool(value: str) -> bool:
    return value.strip().lower() == "true"


def _read_rows(input_path: Path) -> list[CheckoutHour]:
    with input_path.open(newline="", encoding="utf-8") as handle:
        raw_rows = list(csv.DictReader(handle))

    required = {
        "time",
        "today",
        "baseline",
        "absolute_deviation",
        "relative_deviation",
        "is_material",
        "direction",
        "zero_gap",
        "severity_score",
    }
    if not raw_rows or not required.issubset(raw_rows[0].keys()):
        raise ValueError(
            f"{input_path} must be generated by scripts/checkout_analysis.py before charts can be rendered."
        )

    rows: list[CheckoutHour] = []
    for row in raw_rows:
        rows.append(
            CheckoutHour(
                time=row["time"],
                today=float(row["today"]),
                baseline=float(row["baseline"]),
                absolute_deviation=float(row["absolute_deviation"]),
                relative_deviation=float(row["relative_deviation"]),
                is_material=_parse_bool(row["is_material"]),
                direction=row["direction"],
                zero_gap=_parse_bool(row["zero_gap"]),
                severity_score=float(row["severity_score"]),
            )
        )
    return rows


def _format_number(value: float) -> str:
    rounded = round(value, 1)
    if rounded.is_integer():
        return str(int(rounded))
    return f"{rounded:.1f}"


def _format_percent(value: float) -> str:
    return f"{value * 100:+.1f}%"


def _longest_zero_gap(rows: list[CheckoutHour]) -> tuple[int, int, int]:
    best_length = 0
    best_start = -1
    best_end = -1
    current_length = 0
    current_start = -1
    for idx, row in enumerate(rows):
        if row.zero_gap:
            if current_length == 0:
                current_start = idx
            current_length += 1
            if current_length > best_length:
                best_length = current_length
                best_start = current_start
                best_end = idx
        else:
            current_length = 0
            current_start = -1
    return best_length, best_start, best_end


def _build_clusters(rows: list[CheckoutHour]) -> list[FocusCluster]:
    clusters: list[FocusCluster] = []
    idx = 0
    while idx < len(rows):
        direction = rows[idx].direction
        if direction == "normal":
            idx += 1
            continue

        start_idx = idx
        score = 0.0
        peak_idx = idx
        peak_score = rows[idx].severity_score
        has_zero_gap = rows[idx].zero_gap

        while idx < len(rows) and rows[idx].direction == direction:
            row = rows[idx]
            score += row.severity_score
            has_zero_gap = has_zero_gap or row.zero_gap
            if row.severity_score > peak_score:
                peak_idx = idx
                peak_score = row.severity_score
            idx += 1

        clusters.append(
            FocusCluster(
                direction=direction,
                start_idx=start_idx,
                end_idx=idx - 1,
                score=round(score, 4),
                peak_idx=peak_idx,
                has_zero_gap=has_zero_gap,
            )
        )
    return clusters


def _has_recovery_signal(rows: list[CheckoutHour], *, watch_signal: bool) -> bool:
    if not watch_signal or len(rows) < 3:
        return False

    late_rows = rows[-3:]
    if any(row.baseline <= 0 for row in late_rows):
        return False
    if any(abs(row.relative_deviation) > 0.30 for row in late_rows):
        return False
    if any(abs(row.relative_deviation) > 0.45 for row in late_rows):
        return False

    earlier_issue = any(row.direction != "normal" for row in rows[:-3])
    return earlier_issue


def _classify(rows: list[CheckoutHour]) -> Verdict:
    total_today = sum(row.today for row in rows)
    total_baseline = sum(row.baseline for row in rows)
    net_relative = (total_today - total_baseline) / total_baseline if total_baseline else 0.0
    material_hours = [row for row in rows if row.direction != "normal" or row.zero_gap]
    zero_gap_length, zero_gap_start, _ = _longest_zero_gap(rows)
    surges_before_gap = sum(
        1
        for idx, row in enumerate(rows)
        if row.direction == "surge" and (zero_gap_start == -1 or idx < zero_gap_start)
    )

    watch_signal = abs(net_relative) >= 0.10 or len(material_hours) >= 3
    if zero_gap_length >= 2 and surges_before_gap >= 2:
        return Verdict(
            label="Investigate Now",
            level="investigate now",
            summary=(
                "Healthy morning demand gave way to a multi-hour checkout gap. "
                "Structural interruption risk outranks broad uplift, so this checkout comes first."
            ),
            investigate_first=True,
        )
    if _has_recovery_signal(rows, watch_signal=watch_signal):
        return Verdict(
            label="Recovering",
            level="recovering",
            summary="Earlier disruption has eased and the late-day hours are back near expected levels.",
            investigate_first=False,
        )
    if watch_signal:
        if net_relative >= 0 and any(row.direction == "drop" for row in rows) and any(
            row.direction == "surge" for row in rows
        ):
            summary = (
                "Soft morning performance was followed by elevated later hours. "
                "Keep this checkout on watch, but broad uplift still ranks below interruption risk elsewhere."
            )
        elif net_relative >= 0:
            summary = (
                "The day is running above expected without an outage pattern. "
                "Keep it on watch, because broad uplift alone does not outrank a structural interruption."
            )
        else:
            summary = "Several material hours are running below expected. Keep this checkout on watch."
        return Verdict(
            label="Watch",
            level="watch",
            summary=summary,
            investigate_first=False,
        )
    return Verdict(
        label="Normal",
        level="normal",
        summary="Observed behavior is close to expected levels with no clear investigation trigger.",
        investigate_first=False,
    )


def _band_bounds(
    start_idx: int,
    end_idx: int,
    x_positions: list[float],
    *,
    left: float,
    right: float,
) -> tuple[float, float]:
    if len(x_positions) == 1:
        return left, right
    start_x = left if start_idx == 0 else (x_positions[start_idx - 1] + x_positions[start_idx]) / 2
    end_x = right if end_idx == len(x_positions) - 1 else (x_positions[end_idx] + x_positions[end_idx + 1]) / 2
    return start_x, end_x


def _line_points(
    values: list[float],
    x_positions: list[float],
    *,
    chart_top: float,
    chart_bottom: float,
    max_value: float,
) -> str:
    if not values:
        return ""
    height = chart_bottom - chart_top
    points = []
    for idx, value in enumerate(values):
        x = x_positions[idx]
        if max_value:
            y = chart_bottom - (value / max_value) * height
        else:
            y = chart_bottom
        points.append(f"{x:.2f},{y:.2f}")
    return " ".join(points)


def _value_to_y(value: float, *, chart_top: float, chart_bottom: float, max_value: float) -> float:
    if max_value <= 0:
        return chart_bottom
    height = chart_bottom - chart_top
    return chart_bottom - (value / max_value) * height


def _cluster_zero_gap_state(cluster_rows: list[CheckoutHour]) -> tuple[bool, list[str]]:
    zero_gap_times = [row.time for row in cluster_rows if row.zero_gap]
    return bool(cluster_rows) and len(zero_gap_times) == len(cluster_rows), zero_gap_times


def _cluster_label(cluster: FocusCluster, rows: list[CheckoutHour]) -> str:
    cluster_rows = rows[cluster.start_idx : cluster.end_idx + 1]
    is_full_zero_gap_cluster, _ = _cluster_zero_gap_state(cluster_rows)
    start_time = rows[cluster.start_idx].time
    end_time = rows[cluster.end_idx].time
    window = start_time if start_time == end_time else f"{start_time}-{end_time}"
    signal = "drop" if cluster.direction == "drop" else "surge"
    if cluster.direction == "drop" and is_full_zero_gap_cluster:
        signal = "zero-gap drop"
    return f"{window} {signal}"


def _cluster_detail(cluster: FocusCluster, rows: list[CheckoutHour]) -> str:
    cluster_rows = rows[cluster.start_idx : cluster.end_idx + 1]
    is_full_zero_gap_cluster, zero_gap_times = _cluster_zero_gap_state(cluster_rows)
    total_today = sum(row.today for row in cluster_rows)
    total_baseline = sum(row.baseline for row in cluster_rows)
    relative = (total_today - total_baseline) / total_baseline if total_baseline else 0.0
    detail = (
        f"Today {total_today:.0f} vs expected {total_baseline:.1f} "
        f"({_format_percent(relative)})"
    )
    if cluster.direction == "drop" and zero_gap_times and not is_full_zero_gap_cluster:
        detail = f"{detail}; zero-gap at {', '.join(zero_gap_times)}"
    return detail


def _card(
    *,
    x: float,
    y: float,
    width: float,
    height: float,
    label: str,
    value: str,
) -> str:
    return (
        f'<rect x="{x:.2f}" y="{y:.2f}" width="{width:.2f}" height="{height:.2f}" '
        f'rx="16" fill="{COLORS["panel"]}" stroke="{COLORS["panel_border"]}" />'
        f'<text x="{x + 18:.2f}" y="{y + 28:.2f}" font-size="13" fill="{COLORS["muted"]}">{label}</text>'
        f'<text x="{x + 18:.2f}" y="{y + 62:.2f}" font-size="28" font-weight="700" fill="{COLORS["title"]}">{value}</text>'
    )


def _text_block(*, x: float, y: float, width_chars: int, line_height: int, text: str) -> str:
    lines = textwrap.wrap(text, width=width_chars) or [text]
    tspans = []
    for idx, line in enumerate(lines):
        dy = 0 if idx == 0 else line_height
        tspans.append(f'<tspan x="{x:.2f}" dy="{dy}">{line}</tspan>')
    return "".join(tspans)


def generate_chart(input_path: Path, output_path: Path, title: str) -> None:
    rows = _read_rows(input_path)
    verdict = _classify(rows)
    all_clusters = _build_clusters(rows)
    focus_clusters = sorted(all_clusters, key=lambda cluster: (-cluster.score, cluster.start_idx))[:4]

    total_today = sum(row.today for row in rows)
    total_baseline = sum(row.baseline for row in rows)
    net_relative = (total_today - total_baseline) / total_baseline if total_baseline else 0.0

    width, height = 1260, 760
    chart_left, chart_top = 80.0, 240.0
    chart_right, chart_bottom = 820.0, 620.0
    sidebar_left, sidebar_top = 860.0, 240.0
    sidebar_width = 320.0
    sidebar_height = 400.0
    card_y, card_height = 102.0, 88.0
    card_width = 252.0
    card_gap = 18.0
    summary_width_chars = 40
    summary_line_height = 17
    summary_text_y = sidebar_top + 58
    summary_lines = textwrap.wrap(verdict.summary, width=summary_width_chars) or [verdict.summary]
    summary_height = 13 + max(0, len(summary_lines) - 1) * summary_line_height
    summary_bottom = summary_text_y + summary_height

    hours = [row.time for row in rows]
    step_x = (chart_right - chart_left) / max(1, len(hours) - 1)
    x_positions = [chart_left + step_x * idx for idx in range(len(hours))]
    max_value = max(
        max((row.today for row in rows), default=0.0),
        max((row.baseline for row in rows), default=0.0),
    )
    max_value = max(max_value, 1.0)

    today_points = _line_points(
        [row.today for row in rows],
        x_positions,
        chart_top=chart_top,
        chart_bottom=chart_bottom,
        max_value=max_value,
    )
    baseline_points = _line_points(
        [row.baseline for row in rows],
        x_positions,
        chart_top=chart_top,
        chart_bottom=chart_bottom,
        max_value=max_value,
    )

    badge_fill = COLORS[f'badge_{verdict.level}']
    badge_text = COLORS[f'badge_{verdict.level}_text']

    grid = []
    for idx in range(6):
        y = chart_top + idx * (chart_bottom - chart_top) / 5
        label_value = max_value * (1 - idx / 5)
        grid.append(
            f'<line x1="{chart_left:.2f}" y1="{y:.2f}" x2="{chart_right:.2f}" y2="{y:.2f}" '
            f'stroke="{COLORS["grid"]}" />'
        )
        grid.append(
            f'<text x="{chart_left - 18:.2f}" y="{y + 4:.2f}" font-size="11" text-anchor="end" '
            f'fill="{COLORS["muted"]}">{label_value:.0f}</text>'
        )

    labels = []
    for idx, hour in enumerate(hours):
        labels.append(
            f'<text x="{x_positions[idx]:.2f}" y="{chart_bottom + 28:.2f}" font-size="10" '
            f'text-anchor="middle" fill="{COLORS["muted"]}">{hour}</text>'
        )

    bands = []
    for cluster in sorted(focus_clusters, key=lambda current: current.start_idx):
        x0, x1 = _band_bounds(cluster.start_idx, cluster.end_idx, x_positions, left=chart_left, right=chart_right)
        fill = COLORS["surge_fill"] if cluster.direction == "surge" else COLORS["drop_fill"]
        opacity = 0.28 if cluster.direction == "surge" else 0.36
        bands.append(
            f'<rect x="{x0:.2f}" y="{chart_top:.2f}" width="{max(6.0, x1 - x0):.2f}" '
            f'height="{chart_bottom - chart_top:.2f}" fill="{fill}" opacity="{opacity:.2f}" />'
        )

    markers = []
    sidebar_items = []
    sidebar_item_gap = 8.0
    sidebar_item_top = summary_bottom + 18.0
    sidebar_item_bottom = sidebar_top + sidebar_height - 16.0
    available_sidebar_item_height = sidebar_item_bottom - sidebar_item_top
    sidebar_item_height = 72.0
    if focus_clusters:
        sidebar_item_height = max(
            56.0,
            min(
                72.0,
                (available_sidebar_item_height - sidebar_item_gap * (len(focus_clusters) - 1))
                / len(focus_clusters),
            ),
        )
    for item_idx, cluster in enumerate(focus_clusters, start=1):
        peak_row = rows[cluster.peak_idx]
        peak_x = x_positions[cluster.peak_idx]
        peak_y = _value_to_y(
            peak_row.today,
            chart_top=chart_top,
            chart_bottom=chart_bottom,
            max_value=max_value,
        )
        marker_fill = COLORS["surge_stroke"] if cluster.direction == "surge" else COLORS["drop_stroke"]
        markers.append(
            f'<circle cx="{peak_x:.2f}" cy="{peak_y:.2f}" r="11" fill="{marker_fill}" stroke="white" stroke-width="2" />'
            f'<text x="{peak_x:.2f}" y="{peak_y + 4:.2f}" font-size="10" text-anchor="middle" '
            f'fill="white" font-weight="700">{item_idx}</text>'
        )

        item_top = sidebar_item_top + (item_idx - 1) * (sidebar_item_height + sidebar_item_gap)
        item_badge_center_y = item_top + 22.0
        item_title_y = item_top + 20.0
        item_detail_y = item_top + 42.0
        sidebar_items.append(
            f'<rect x="{sidebar_left:.2f}" y="{item_top:.2f}" width="{sidebar_width:.2f}" height="{sidebar_item_height:.2f}" '
            f'rx="14" fill="{COLORS["panel"]}" stroke="{COLORS["panel_border"]}" />'
            f'<circle cx="{sidebar_left + 22:.2f}" cy="{item_badge_center_y:.2f}" r="12" fill="{marker_fill}" />'
            f'<text x="{sidebar_left + 22:.2f}" y="{item_badge_center_y + 4:.2f}" font-size="10" text-anchor="middle" '
            f'fill="white" font-weight="700">{item_idx}</text>'
            f'<text x="{sidebar_left + 44:.2f}" y="{item_title_y:.2f}" font-size="13" font-weight="700" '
            f'fill="{COLORS["title"]}">{_cluster_label(cluster, rows)}</text>'
            f'<text x="{sidebar_left + 44:.2f}" y="{item_detail_y:.2f}" font-size="12" fill="{COLORS["muted"]}">'
            f'{_cluster_detail(cluster, rows)}</text>'
        )

    cards = [
        _card(x=80, y=card_y, width=card_width, height=card_height, label="Today total", value=_format_number(total_today)),
        _card(
            x=80 + (card_width + card_gap),
            y=card_y,
            width=card_width,
            height=card_height,
            label="Expected total",
            value=_format_number(total_baseline),
        ),
        _card(
            x=80 + 2 * (card_width + card_gap),
            y=card_y,
            width=card_width,
            height=card_height,
            label="Net deviation",
            value=_format_percent(net_relative),
        ),
        _card(
            x=80 + 3 * (card_width + card_gap),
            y=card_y,
            width=card_width,
            height=card_height,
            label="Investigate first",
            value="Yes" if verdict.investigate_first else "No - secondary",
        ),
    ]

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">
<rect width="100%" height="100%" fill="{COLORS["bg"]}"/>
<text x="80" y="44" font-size="28" font-weight="700" fill="{COLORS["title"]}">{title}</text>
<text x="80" y="72" font-size="14" fill="{COLORS["muted"]}">Question: does this checkout deserve investigation before the others?</text>
<rect x="1015" y="28" width="165" height="40" rx="20" fill="{badge_fill}" />
<text x="1097.5" y="54" font-size="15" font-weight="700" text-anchor="middle" fill="{badge_text}">{verdict.label.upper()}</text>
{''.join(cards)}
<rect x="{chart_left:.2f}" y="{chart_top:.2f}" width="{chart_right - chart_left:.2f}" height="{chart_bottom - chart_top:.2f}" rx="18" fill="{COLORS["panel"]}" stroke="{COLORS["panel_border"]}" />
<text x="{chart_left + 18:.2f}" y="{chart_top - 16:.2f}" font-size="15" font-weight="700" fill="{COLORS["title"]}">Today vs expected hourly volume</text>
<text x="{chart_left + 18:.2f}" y="{chart_top + 24:.2f}" font-size="12" fill="{COLORS["muted"]}">Expected is the blended baseline from recent historical references; yesterday alone remains evidence but is noisier on its own.</text>
{''.join(grid)}
{''.join(bands)}
<line x1="{chart_left:.2f}" y1="{chart_bottom:.2f}" x2="{chart_right:.2f}" y2="{chart_bottom:.2f}" stroke="{COLORS["axis"]}" />
<line x1="{chart_left:.2f}" y1="{chart_top:.2f}" x2="{chart_left:.2f}" y2="{chart_bottom:.2f}" stroke="{COLORS["axis"]}" />
<polyline fill="none" stroke="{COLORS["baseline"]}" stroke-width="3" stroke-dasharray="10 8" points="{baseline_points}" />
<polyline fill="none" stroke="{COLORS["today"]}" stroke-width="4" points="{today_points}" />
{''.join(markers)}
{''.join(labels)}
<text x="{chart_left + 18:.2f}" y="{chart_bottom + 56:.2f}" font-size="12" fill="{COLORS["today"]}">Today</text>
<text x="{chart_left + 90:.2f}" y="{chart_bottom + 56:.2f}" font-size="12" fill="{COLORS["baseline"]}">Expected</text>
<text x="{chart_left + 186:.2f}" y="{chart_bottom + 56:.2f}" font-size="12" fill="{COLORS["surge_stroke"]}">Surge window</text>
<text x="{chart_left + 306:.2f}" y="{chart_bottom + 56:.2f}" font-size="12" fill="{COLORS["drop_stroke"]}">Drop window</text>
<rect x="{sidebar_left:.2f}" y="{sidebar_top:.2f}" width="{sidebar_width:.2f}" height="{sidebar_height:.2f}" rx="18" fill="{COLORS["panel"]}" stroke="{COLORS["panel_border"]}" />
<text x="{sidebar_left + 20:.2f}" y="{sidebar_top + 32:.2f}" font-size="17" font-weight="700" fill="{COLORS["title"]}">Why this verdict</text>
<text x="{sidebar_left + 20:.2f}" y="{summary_text_y:.2f}" font-size="13" fill="{COLORS["muted"]}">{_text_block(x=sidebar_left + 20, y=summary_text_y, width_chars=summary_width_chars, line_height=summary_line_height, text=verdict.summary)}</text>
{''.join(sidebar_items) if sidebar_items else f'<text x="{sidebar_left + 20:.2f}" y="{summary_bottom + 36:.2f}" font-size="13" fill="{COLORS["muted"]}">No material windows crossed the investigation threshold.</text>'}
<text x="80" y="704" font-size="12" fill="{COLORS["muted"]}">Evidence review prioritizes suspicious windows. It does not prove business or system root cause on its own.</text>
</svg>"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(svg, encoding="utf-8")


if __name__ == "__main__":
    generate_chart(
        Path("database/report/checkout_1_anomaly.csv"),
        Path("charts/checkout_1.svg"),
        "Checkout 1 Investigation Summary",
    )
    generate_chart(
        Path("database/report/checkout_2_anomaly.csv"),
        Path("charts/checkout_2.svg"),
        "Checkout 2 Investigation Summary",
    )
